// <auto-generated />
using System;
using DAL.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241215152624_AddServiceCardToUser")]
    partial class AddServiceCardToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.CopyTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfCopies")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CopyTransactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1.00m,
                            Date = new DateTime(2024, 12, 15, 15, 26, 23, 989, DateTimeKind.Utc).AddTicks(4297),
                            NumberOfCopies = 10,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 0.50m,
                            Date = new DateTime(2024, 12, 15, 15, 26, 23, 989, DateTimeKind.Utc).AddTicks(5533),
                            NumberOfCopies = 5,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("DAL.Models.Event", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AvailableTickets")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TicketPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = "E1",
                            AvailableTickets = 100,
                            Date = new DateTime(2024, 12, 30, 15, 26, 23, 989, DateTimeKind.Utc).AddTicks(5946),
                            Name = "University Concert",
                            TicketPrice = 50.0m
                        },
                        new
                        {
                            Id = "E2",
                            AvailableTickets = 50,
                            Date = new DateTime(2024, 12, 25, 15, 26, 23, 989, DateTimeKind.Utc).AddTicks(6404),
                            Name = "Science Seminar",
                            TicketPrice = 25.0m
                        });
                });

            modelBuilder.Entity("DAL.Models.EventTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EventTickets");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 1500m,
                            Name = "Alessandro Chiolini",
                            ServiceCard = "CARD123456"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 1000m,
                            Name = "Julien Blanch-Lanao",
                            ServiceCard = "CARD654321"
                        },
                        new
                        {
                            Id = 3,
                            Balance = 1200m,
                            Name = "Gian-Luca Gloor",
                            ServiceCard = "CARD987654"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
